### PR TITLE
Add 36 names

### PR DESCRIPTION
**Pull request by emoose**
Just found https://github.com/0x1F9F1/joaat-in-the-middle which can bruteforce pretty quick, but gives a lot of false positives, I'll try going through some of the rest with it and see what it gives us.

### CODE REVIEW

**Review by TheRouletteBoi — APPROVED** [review]

**Comment by emoose** [comment]
Using these 3: 
[rdr_lists.zip](https://github.com/user-attachments/files/17758472/rdr_lists.zip)

The words.txt file has the words with underscores attached, and end.txt has them without it for the last word

Then I just run the bruter like
`jitm $9A4CD54B output.txt words.txt end.txt`
Then look at output.txt, if nothing looks good then add another words.txt and keep adding them
`jitm $9A4CD54B output.txt words.txt words.txt end.txt`
If you know the start/end of the string you can include it with $whatever as well
`jitm $9A4CD54B output.txt $is_current_camera_ words.txt words.txt end.txt`
`jitm $9A4CD54B output.txt $is_current_ words.txt words.txt $transitioning`

alphanum.txt can be used instead of words to try bruting a-z for that part too

Think I might have a bunch of crap in that words list that never actually get used though, probably makes it put out a lot more false positives :/

**Comment by TheRouletteBoi** [comment]
Which one were you using before [joaat-in-the-middle](https://github.com/0x1F9F1/joaat-in-the-middle)? I've been using the GTAV ones from Alexander Blade's documentation

[native_brute_forcing.zip](https://github.com/user-attachments/files/17758703/native_brute_forcing.zip)
[rdrstringsdump.txt](https://github.com/user-attachments/files/17758707/rdrstringsdump.txt)

**Comment by emoose** [comment]
Oh neat hadn't seen those before, ended up writing my own messy tool for it, got it at a decent speed (800-1M hashes/s) but it uses a lot of hardcoded stuff, have to rebuild to switch between wordlists/alphanum and stuff like that.

joaat in the middle seems a lot faster than what I had though, but does give a ton of false positives to go through... will have to give nativebruter a try soon, maybe lists it has could help with a few names.

btw do you know if there were ever any script editors made for switch/pc RDR? I know magicrdr has a script decompiler but haven't been able to find any disassembler/editor for it, did find an old editor for RDR 360 but couldn't even find any working links for that anymore: https://www.se7ensins.com/proxy.php?image=http%3A%2F%2Fgyazo.com%2F74d4ad70fc23436816f378ad58014fa1.png&hash=7bf6c323b7695ac375f8124019b61fbb

**Comment by TheRouletteBoi** [comment]
> Oh neat hadn't seen those before, ended up writing my own messy tool for it, got it at a decent speed (800M-1B hashes/s) but it uses a lot of hardcoded stuff, have to rebuild to switch between wordlists/alphanum and stuff like that.
> 
> joaat in the middle seems a lot faster than what I had though, but does give a ton of false positives to go through... will have to give nativebruter a try soon, maybe lists it has could help with a few names.
> 
> btw do you know if there were ever any script editors made for switch/pc RDR? I know magicrdr has a script decompiler but haven't been able to find any disassembler/editor for it, did find a pic of an old editor for RDR 360 but couldn't even find any working links for that anymore: https://www.se7ensins.com/proxy.php?image=http%3A%2F%2Fgyazo.com%2F74d4ad70fc23436816f378ad58014fa1.png&hash=7bf6c323b7695ac375f8124019b61fbb
> 
> atm I've been hex editing scripts to change stuff, wish there was something like that XSC editor instead

Try checking out this one. https://github.com/NativeFunction/RASM

**Comment by emoose** [comment]
Ahh that's perfect, not sure how I missed that lol, looks like it only has X360/PS3 support but hopefully can add PC stuff for it, ty!

**Pull request merged**
