### PR TITLE
Name 902 natives

### PR DESCRIPTION
**Pull request by emoose**
Known names 1963 -> 2865

Majority are from magicrdr, but was also able to find ~146 names that were missing there (magicrdr does also have a lot of guessed names that I didn't include here)

Verified hashes with a quick script, found 1 or 2 existing ones that didn't match up properly and added underscores for them, should all match up fine.

### CODE REVIEW

**Comment by emoose** [comment]
@TheRouletteBoi thanks for the quick merge, btw do you know where the categories for these natives come from? Are they from the game itself?
I noticed some of them are in weird categories, like SOCIALCLUB has IS_MISSION_SCRIPT / GET_GAME_STATE / etc inside it
(in switch the func that creates those natives is `rdr2scripting::game::SetupCommands`)
Also the script cmds in AI2/AI3/AI4 seem to come from funcs like `aiScript::SetupScriptCommandsPerception` `aiScript::SetupScriptCommandsRide`
Maybe it's worth renaming them to be closer to those func names? would you be fine with that?

**Comment by emoose** [comment]
Posted a quick rename at https://github.com/emoose/rdr-nativedb-data/commit/17817ffd6680a6db81c41a9ccfde057f33322bab, haven't sorted them alphabetically like they were before yet though

Also added 12 natives from NSW that were missing, haven't checked PC yet (did notice a lot of the NET natives were missing on PC though 😿)

**Comment by emoose** [comment]
Added ~64 PC natives at https://github.com/emoose/rdr-nativedb-data/commit/4387adddc6f3410555770c7e86fb990dafe01bda too
Seems they added a whole new category just for some PC funcs, looks like all they do is each set an individual bool to true, and then some func related to black-bars checks if any of those bools are set, odd that they didn't just create a single script func for that.

Also in between IS_SWITCH and IS_PC is an odd 0xFC7766A0 hash, haven't been able to crack it yet, maybe some other planned platform? 😸

**Comment by TheRouletteBoi** [comment]
> @TheRouletteBoi thanks for the quick merge, btw do you know where the categories for these natives come from? Are they from the game itself? I noticed some of them are in odd categories, like SOCIALCLUB has IS_MISSION_SCRIPT / GET_GAME_STATE / etc inside it (in switch the func that creates those natives is `rdr2scripting::game::SetupCommands`) Also the script cmds in AI2/AI3/AI4 seem to come from funcs like `aiScript::SetupScriptCommandsPerception` `aiScript::SetupScriptCommandsRide` Maybe it's worth renaming them to be closer to those func names? something like AIPERCEPTION / AIRIDE Would you be fine with that?

The categories for the natives actually come from separate subroutines in the game executable, which then determine the namespace name. They were loosely based on observed functions and patterns. But it’s true they aren’t always spot on. The SOCIALCLUB natives, for instance do have some unexpected functions, like IS_MISSION_SCRIPT and GET_GAME_STATE, which could definitely use some recategorization for clarity. I appreciate the renaming work you did already. Also does the PC version of the game come with symbols?

**Comment by TheRouletteBoi** [comment]
If the PC version has symbols then we can just use the namespace based on the symbol like you mentioned

**Comment by emoose** [comment]
Nah no symbols on PC afaik sadly, luckily a lot of the symbols from switch do transfer over fine though, but we won't have any names for any of the new PC only things :(

Will see if I can get the json alphabetized and make a PR for it soon.

**Pull request merged**
